### PR TITLE
Update csproject for single file builds

### PR DESCRIPTION
**Pull request by BOLL7708**
This is Jeppe's commit, can I still make PR to my own project for it?

### CODE REVIEW

**Comment by BOLL7708** [comment]
Hello dear contributor! 

I have re-licensed this project as GPLv3, and I have plans to combine my various VR applications into a single toolkit and publish that freely on Steam. That requires the project to be licensed to me using LGPLv3 as well, as Steam does not allow the full GPLv3 license, so I've added a new Contributor License Agreement to this project to facilitate this.

I hope you are willing to sign this agreement to accept the new licensing changes. You can do this by editing the CLA.md file directly here on GitHub and submit it as a pull request. Any contribution that does not get re-licensed will be eventually be removed from the project. If you have any questions, don't hesitate to reply to me here.

Thank you for your consideration!

**Comment by BOLL7708** [comment]
@jeppevinkel I realize you likely didn't get _this_ email, as I apparently did the pull request from your fork, with your commits. You are still listed as a contributor for this project though, so please read the above. Yeah I'm writing this as if you hadn't already signed for four other projects 😅

**Comment by jeppevinkel** [comment]
I refuse to sign this one due to how awesome my work was :P

**Comment by jeppevinkel** [comment]
P.s. You are correct, I didn't get an email since this was your PR

**Comment by BOLL7708** [comment]
Hah. I think most contributions to most projects I have, have been small tiny adjustments. Except your contributions to the pipe application and possibly EasyOpenVR. If nobody else replies or signs, I don't think it'll be a huge loss, and I'll revert their commits. 

I'm happy to have gotten this far by this point and I'll await other responses until the PanGui library comes out and I'll start work on the single shared application, making future management of contributions a bit smoother.

Will also have to read up on the verified commits stuff, to see if it is something I should be adopting. Cheers!

**Pull request merged**
