### PR TITLE
Add Shutdown Scripts

### PR DESCRIPTION
**Pull request by piepie62**
Do note: this is my first time using the OpenVR API, so I'm not certain whether this is the best way to actually implement this. It does work, though.

### CODE REVIEW

**Comment by BOLL7708** [comment]
It's basically what we have to do yeah, poll the even queue to look for the quit event. I'm a bit swamped with other projects, but I'll look at this hopefully within a week. The whole constant polling was the reason why I dismissed this feature in the first place, buuuut, I figure we could just look for shutdown scripts at startup, and if none exist just terminate and that's that. Thanks for doing this, again I'll get to it, soon.

**Comment by piepie62** [comment]
That's a good point/optimization that I hadn't thought of. Just a note, I chose the event polling timeout to be a tenth of a second on a whim; it's possible that a full second could work as well, reducing overhead a bit with no huge cost.

**Comment by LonleyViper** [comment]
I love you guys! In terms of CPU hit. What are we talking?

**Comment by LonleyViper** [comment]
Dumb question - are you compiling this for release? No biggie I can do it from source if you're busy :)

**Comment by BOLL7708** [comment]
@LonleyViper I have been working on it since merging it, there is now a new release with this built in. I reworked a bunch of the code to clean it up a bit, and from my initial testing it seems to do exactly what it is supposed to do. If you find any problems with it you know where to report them 😉

**Comment by BOLL7708** [comment]
Hello dear contributor! 

I have re-licensed this project as GPLv3, and I have plans to combine my various VR applications into a single toolkit and publish that freely on Steam. That requires the project to be licensed to me using LGPLv3 as well, as Steam does not allow the full GPLv3 license, so I've added a new Contributor License Agreement to this project to facilitate this.

I hope you are willing to sign this agreement to accept the new licensing changes. You can do this by editing the CLA.md file directly here on GitHub and submit it as a pull request. Any contribution that does not get re-licensed will be eventually be removed from the project. If you have any questions, don't hesitate to reply to me here.

Thank you for your consideration!

**Pull request merged**
